	<div id="secondLevelContent">
			<div id="thirdLevelHeader">
				<div class="breadcrumb hasIcon iconBannersLarge ">
					<h3 class="noBreadcrumb">
	
					<span class="label"><?php echo $layout_title; ?></span>
					</h3>
				</div>
			</div>
			<div id="thirdLevelContent" style="min-height: 456px;">
				<!--this is where status messages will be put
				<div id="thirdLevelTools">
					<div id="messagePlaceholder" class="messagePlaceholder"></div>
					<ul class="contextContainer"></ul>
				</div> -->
				<!--this is where the actual content of hte layout will also be put --->
			</div>
	</div>  
<!--
</div>
<div name="setting_dialog-message" id="setting_dialog-message" title="Message">
            <p class="messsage">
            </p>
        </div>
        <div name="setting_dialog-confirm" id="setting_dialog-confirm  title="Confirmation">
             <p class="messsage">
            </p>
        </div>
    </body>
</html>
-->
