    <body class="hasInterface hasGradient hasSidebar">
    <input type="hidden" name="search_user_url" id="search_user_url" value="/yapp_test/user/search_user">
    
        <div id="oaHeader">
            <div id="oaNavigationExtraTop">

                <ul id="UL_1">

					                                                  <li id="LI_77">
                        <a href="#" id="A_78"><i id="I_79"></i><span id="SPAN_80"></span></a>
                    </li>
                    <li id="LI_115">
                        <a href="#" id="A_116" ><span id="SPAN_118">                              
                                %%fname%% </span>
                            <i id="I_119" class="fa fa-cog"></i>
                        </a>
                        <ul id="UL_120">                  
                            <li id="LI_127" class="buttonLogout  footer">
                                <a href="/yapp_test/auth/logout" id="A_128">
                                    <i id="I_129"></i>Logout</a>
                            </li>
                        </ul>
                    </li>
                </ul>

            </div>


        </div>

