version: "3"
services:
  web:
    image: nayibor/erl_yaws:0.1.0
    ports:
      - "8002:8002"
      - "8003:8003"
      - "8004:8004"
    volumes:
      - "../../rebar_erlmon/:/opt/erlang/erl_mon"
      - "/tmp/.X11-unix:/tmp/.X11-unix"
    stdin_open: true
    tty: true
